<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>3DPlatformer</AssemblyName>
    <AssemblyTitle>3D Platformer</AssemblyTitle>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\Desktop\Icon.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <DefineConstants Condition="'$(Configuration)' == 'Debug'">$(DefineConstants);DEVMODE</DefineConstants>
    <MonoGamePlatform>Windows</MonoGamePlatform>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Source\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5-preview.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Desktop\Icon.ico">
      <Link>Icon.ico</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="..\Desktop\Icon.ico">
      <LogicalName>Icon.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <Import Project="..\Content\BuildContent.targets" />
</Project>
