<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Platformer3D</AssemblyName>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <DefineConstants Condition="'$(Configuration)' == 'Debug'">$(DefineConstants);DEVMODE</DefineConstants>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Core\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5-preview.*" />
  </ItemGroup>
  <PropertyGroup>
    <MonoGamePlatform>Windows</MonoGamePlatform>
  </PropertyGroup>
  <Import Project="..\Content\BuildContent.targets" />
</Project>
