<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Source\Base\AnimationData.cs" Link="Base\AnimationData.cs" />
    <Compile Include="..\Source\Base\Contact.cs" Link="Base\Contact.cs" />
    <Compile Include="..\Source\Base\ConvexHull.cs" Link="Base\ConvexHull.cs" />
    <Compile Include="..\Source\Base\GameConstants.cs" Link="Base\GameConstants.cs" />
    <Compile Include="..\Source\Base\ModelData.cs" Link="Base\ModelData.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Content.Pipeline" Version="3.8.5-develop.6" />
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5-develop.6" />
    <PackageReference Include="MIConvexHull" Version="1.1.19.1019" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Base\" />
  </ItemGroup>
  
</Project>
